### ISSUE TITLE
gnutls 3.3.9 breaks 64bit build (danetool with undefined reference to `mkstemp')

### ISSUE THREAD

**Issue by abarbieri** [rdp/ffmpeg-windows-build-helpers#58]
on Ubuntu 14.04.1 LTS whilst the 32bit build completes successfully all the way down to ffmpeg, during the 64bit build with the new gnutls v3.3.9 linking danetool.exe throws:
  CCLD     danetool.exe
danetool.o:danetool.c:(.text+0x1266): undefined reference to `mkstemp'
collect2: error: ld returned 1 exit status

previous gnutls 3.2.14 did not experience this error for 64bit build.

**Comment by rdp** [comment]
ok reverted temporarily thanks for the note

**Comment by rdp** [comment]
ok fixed with work around from https://groups.google.com/forum/#!topic/roger-projects/-0OKk0RaQuI

**Comment by abarbieri** [comment]
this is what the guys at gcc/gfortran did few years ago to resolve the mkstemp issue with mingw64:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43844

mingw64 should also cope with mkstemp as shown here:
https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-tools/widl/src/port/port.c

**Comment by abarbieri** [comment]
mingw_w64 is now at version 3.3.0, may want to bump up mingw-w64-build-3.6.4.local to make use of this latest stable version.

**Comment by rdp** [comment]
yeah I did that yesterday, but no difference.  And they might never
implement it LOL.  However the gnutls guys said they would create a
workaround...which might be the right way...
