### ISSUE TITLE
Win32 build fails in glib

### ISSUE THREAD

**Issue by rboy1** [rdp/ffmpeg-windows-build-helpers#605]
Ubuntu 18.10 x64 building ffmpeg x86

The build fails when trying to build glib
> [121/520] Compiling C object glib/libglib-2.0.a.p/gthread-posix.c.obj
FAILED: glib/libglib-2.0.a.p/gthread-posix.c.obj 
/home/c/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-gcc -Iglib/libglib-2.0.a.p -Iglib -I../glib -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wno-unused-parameter -Wno-bad-function-cast -Wno-pedantic -Wno-format-zero-length -Werror=declaration-after-statement -Werror=format=2 -Werror=implicit-function-declaration -Werror=init-self -Werror=missing-include-dirs -Werror=missing-prototypes -Werror=pointer-arith -mms-bitfields -mtune=generic -O3 -pthread '-DG_LOG_DOMAIN="GLib"' -DGLIB_COMPILATION -DPCRE_STATIC -MD -MQ glib/libglib-2.0.a.p/gthread-posix.c.obj -MF glib/libglib-2.0.a.p/gthread-posix.c.obj.d -o glib/libglib-2.0.a.p/gthread-posix.c.obj -c ../glib/gthread-posix.c
../glib/gthread-posix.c: In function 'g_cond_impl_new':
../glib/gthread-posix.c:674:2: error: #error Cannot support GCond on your platform.
 #error Cannot support GCond on your platform.
  ^~~~~
../glib/gthread-posix.c: In function 'g_cond_wait_until':
../glib/gthread-posix.c:922:2: error: #error Cannot support GCond on your platform.
 #error Cannot support GCond on your platform.

**Comment by rdp** [comment]
This is when building the cross compilers?

**Comment by rboy1** [comment]
No, this is in build_glib() which is required for builds_lensfun(). If I don’t include lensfun libraries then it builds fine.

**Comment by rdp** [comment]
hmm just built OK for me with 20.04 ...

**Comment by rboy1** [comment]
Yup it works with 20.04 but not it 18.10, I'm going to close this.

**Comment by rdp** [comment]
Program /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win64/glib-2.64.3/build/gobject/glib-genmarshal found: YES (/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win64/glib-2.64.3/build/gobject/glib-genmarshal)
Configuring glib-mkenums using configuration
Program /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win64/glib-2.64.3/build/gobject/glib-mkenums found: YES (/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win64/glib-2.64.3/build/gobject/glib-mkenums)
Configuring libgobject-2.0.so.0.6400.3-gdb.py using configuration
gobject/meson.build:153: DEPRECATION: Please use the new `install:` kwarg instead of passing `false` to `install_dir:`
Configuring gthread.rc using configuration
Configuring gmoduleconf.h using configuration
Configuring gmodule.rc using configuration
Configuring gnetworking.h using configuration
Configuring gdbus-codegen using configuration
Program /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win64/glib-2.64.3/build/gio/gdbus-2.0/codegen/gdbus-codegen found: YES (/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win64/glib-2.64.3/build/gio/gdbus-2.0/codegen/gdbus-codegen)
Configuring config.py using configuration
Library shlwapi found: YES
Library dnsapi found: YES
Configuring gio.rc using configuration
Run-time dependency libelf found: NO (tried pkgconfig and cmake)
Library elf found: NO
Compiler for C supports arguments -Werror=unused-function: YES (cached)
Library FuzzingEngine skipped: feature oss_fuzz disabled
Program xgettext found: NO
Configuring glib-gettextize using configuration
Configuring config.h using configuration
Build targets in project: 36
Option buildtype is: release [default: debugoptimized]
Found ninja-1.8.2 at /usr/bin/ninja
[15/281] Compiling C object 'glib/4430778@@glib-2.0@sta/gthread-posix.c.obj'.
FAILED: glib/4430778@@glib-2.0@sta/gthread-posix.c.obj
/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32-gcc -Iglib/4430778@@glib-2.0@sta -Iglib -I../glib -I. -I../ -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -std=gnu99 -O3 -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wno-unused-parameter -Wno-bad-function-cast -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Werror=declaration-after-statement -Werror=format=2 -Werror=implicit-function-declaration -Werror=init-self -Werror=missing-include-dirs -Werror=missing-prototypes -Werror=pointer-arith -mms-bitfields -mtune=generic -O3 -pthread '-DG_LOG_DOMAIN="GLib"' -DGLIB_COMPILATION -DPCRE_STATIC -MD -MQ 'glib/4430778@@glib-2.0@sta/gthread-posix.c.obj' -MF 'glib/4430778@@glib-2.0@sta/gthread-posix.c.obj.d' -o 'glib/4430778@@glib-2.0@sta/gthread-posix.c.obj' -c ../glib/gthread-posix.c
../glib/gthread-posix.c: In function 'g_cond_impl_new':
../glib/gthread-posix.c:674:2: error: #error Cannot support GCond on your platform.
 #error Cannot support GCond on your platform.

in 18.04
