### ISSUE TITLE
Error libutvideo version

### ISSUE THREAD

**Issue by muzicman0** [rdp/ffmpeg-windows-build-helpers#124]
I am getting the following error running the script:

ERROR: libutvideo version must be <= 15.3.0.

I have tried it on Ubuntu 15.10, 16.4, as well as using Windows.  Each time it ends with this error.

I will paste the last 50 or 60 lines in below, just in case the error has something to do with the output above.

Cloning into 'ffmpeg_git_with_fdk_aac.tmp'...
remote: Counting objects: 475361, done.
remote: Compressing objects: 100% (630/630), done.
remote: Total 475361 (delta 362), reused 0 (delta 0), pack-reused 474729                  100%
Receiving objects: 100% (475361/475361), 159.86 MiB | 774.00 KiB/s, done.
Resolving deltas: 100% (371215/371215), done.
Checking connectivity... done.
Checking out files: 100% (5835/5835), done.
done downloading ffmpeg_git_with_fdk_aac
Makefile:2: config.mak: No such file or directory
Makefile:66: /common.mak: No such file or directory
Makefile:108: /libavutil/Makefile: No such file or directory
Makefile:108: /library.mak: No such file or directory
Makefile:110: /doc/Makefile: No such file or directory
Makefile:197: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
configuring ffmpeg_git_with_fdk_aac (/cygdrive/c/Users/Steven/Desktop/ffmpeg-windows-build-helpers-master/native_build/ffmpeg_local_builds/sandbox/x86_64/ffmpeg_git_with_fdk_aac) as $ PATH=/cygdrive/c/Users/Steven/Desktop/ffmpeg-windows-build-helpers-master/native_build/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin:/usr/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:%SystemRoot%/system32:%SystemRoot%:%SystemRoot%/System32/Wbem:%SYSTEMROOT%/System32/WindowsPowerShell/v1.0 ./configure --arch=x86_64 --target-os=mingw32 --cross-prefix=/cygdrive/c/Users/Steven/Desktop/ffmpeg-windows-build-helpers-master/native_build/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-libass --enable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --enable-decklink --extra-libs=-loleaut32 --enable-libx264 --enable-libxvid --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype --enable-libopus --enable-frei0r --enable-filter=frei0r --enable-bzlib --enable-libxavs --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-libgme --enable-dxva2 --enable-avisynth --enable-gray --enable-libopenh264 --enable-libmfx --extra-libs=-lpsapi --extra-cflags= --enable-static --disable-shared  --prefix=/cygdrive/c/Users/Steven/Desktop/ffmpeg-windows-build-helpers-master/native_build/ffmpeg_local_builds/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-libfdk-aac --disable-libfaac --enable-nvenc  --enable-runtime-cpudetect
ERROR: libutvideo version must be <= 15.3.0.

**Comment by hydra3333** [comment]
I encountered this message too :)

**Comment by AurelioSilver** [comment]
Caused by this commit: http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=017d42ebc60f66b94d13aeeeabcec284486872e9

But this does not work because version 12.2.1 uses these defines:
#define UTVIDEO_VERSION_MASK     0xffffff00
#define UTVIDEO_VERSION                 0x0c0202100
#define UTVIDEO_VERSION_STR        "12.2.1"

and newer versions use:

#define UTVIDEO_VERSION_MAJOR  16
#define UTVIDEO_VERSION_MINOR   1
#define UTVIDEO_VERSION_BUGFIX  0

But it seems FFmpeg devs want to remove support for it:

https://lists.ffmpeg.org/pipermail/ffmpeg-devel/2016-February/189014.html

**Comment by muzicman0** [comment]
Ok. I think I understand.  Is there anything that can be done to get around this?

**Comment by AurelioSilver** [comment]
Well, do you need the features of libutvideo? If not, you could uncomment "build_libutvideo" in the build script. 

Or
- Patch your ffmpeg source to remove the new version check.
- Open a ticket to ffmpeg to fix their version check to include also older versions and wait until they fixed it.
- Switch to a newer utvideolib with the new version format which is <= 15.3.0.

**Comment by rdp** [comment]
Yeah you could work around it by changing --enable-libutvideo to
--disable-libutvideo in the ffmpeg configure.
Anyway I have attempted to bump the libutvideo to 15.3.0 now, give it a
shot, thanks!

**Comment by muzicman0** [comment]
I have tried removing the --enable-libutvideo altogether...if that works, great...if not, I will start from scratch and try again.  Thanks everyone!

**Comment by muzicman0** [comment]
changed my mind...I went ahead and cancelled the compile I had going (I was only 5 minutes in), and started from scratch.  I will let you know if the new commit works when it is done.

**Comment by AurelioSilver** [comment]
The new utvideolib fails to compile here.

**Comment by muzicman0** [comment]
I am still going, but I had to restart again (ran out of disk space on my VM - Doh!).

What does utvideo get me?  I am looking specifically for ffmpeg with nvenc enabled so that I can leverage my Nvidia GTX960 to render h265 video.  

If I don't need utvideo, then I will just edit the script to disable it, and if needed, remove the entire make section for libutvideo.  will that work?

**Comment by muzicman0** [comment]
Yep...failing for me too...here is the relevant section:

```
making /home/steven/ffmpeg_build/sandbox/x86_64/utvideo-15.3.0 as $ PATH=/home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make CROSS_PREFIX=/home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- DESTDIR=/home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 -j 4

 RM	utv_core/*.o
 RM	utv_core/libutvideo.a
 CXX	utv_core/Codec.o
 CXX	utv_core/CodecBase.o
 CXX	utv_core/DummyCodec.o
 CXX	utv_core/Convert.o
In file included from utv_core/DummyCodec.cpp:4:0:
utv_core/stdafx.h:52:0: warning: "_countof" redefined
 #define _countof(x) (sizeof(x) / sizeof((x)[0]))
 ^
In file included from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/mm_malloc.h:27:0,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:34,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/x86intrin.h:31,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/winnt.h:1521,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/minwindef.h:163,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windef.h:8,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windows.h:69,
                 from utv_core/stdafx.h:30,
                 from utv_core/DummyCodec.cpp:4:
/home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/stdlib.h:299:0: note: this is the location of the previous definition
 #define _countof(_Array) sizeof(*__countof_helper(_Array))
 ^
In file included from utv_core/Convert.cpp:4:0:
utv_core/stdafx.h:52:0: warning: "_countof" redefined
 #define _countof(x) (sizeof(x) / sizeof((x)[0]))
 ^
In file included from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/mm_malloc.h:27:0,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:34,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/x86intrin.h:31,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/winnt.h:1521,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/minwindef.h:163,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windef.h:8,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windows.h:69,
                 from utv_core/stdafx.h:30,
                 from utv_core/Convert.cpp:4:
/home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/stdlib.h:299:0: note: this is the location of the previous definition
 #define _countof(_Array) sizeof(*__countof_helper(_Array))
 ^
In file included from utv_core/DummyCodec.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
In file included from utv_core/Codec.cpp:4:0:
utv_core/stdafx.h:52:0: warning: "_countof" redefined
 #define _countof(x) (sizeof(x) / sizeof((x)[0]))
 ^
In file included from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/mm_malloc.h:27:0,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:34,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/x86intrin.h:31,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/winnt.h:1521,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/minwindef.h:163,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windef.h:8,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windows.h:69,
                 from utv_core/stdafx.h:30,
                 from utv_core/Codec.cpp:4:
/home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/stdlib.h:299:0: note: this is the location of the previous definition
 #define _countof(_Array) sizeof(*__countof_helper(_Array))
 ^
<builtin>: recipe for target 'utv_core/DummyCodec.o' failed
make: *** [utv_core/DummyCodec.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from utv_core/Convert.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
In file included from utv_core/CodecBase.cpp:4:0:
utv_core/stdafx.h:52:0: warning: "_countof" redefined
 #define _countof(x) (sizeof(x) / sizeof((x)[0]))
 ^
In file included from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/mm_malloc.h:27:0,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/xmmintrin.h:34,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/5.3.0/include/x86intrin.h:31,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/winnt.h:1521,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/minwindef.h:163,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windef.h:8,
                 from /home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/windows.h:69,
                 from utv_core/stdafx.h:30,
                 from utv_core/CodecBase.cpp:4:
/home/steven/ffmpeg_build/sandbox/cross_compilers/mingw-w64-x86_64/include/stdlib.h:299:0: note: this is the location of the previous definition
 #define _countof(_Array) sizeof(*__countof_helper(_Array))
 ^
In file included from utv_core/Codec.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
<builtin>: recipe for target 'utv_core/Convert.o' failed
make: *** [utv_core/Convert.o] Error 1
compilation terminated.
<builtin>: recipe for target 'utv_core/Codec.o' failed
make: *** [utv_core/Codec.o] Error 1
In file included from utv_core/CodecBase.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
<builtin>: recipe for target 'utv_core/CodecBase.o' failed
make: *** [utv_core/CodecBase.o] Error 1
```

**Comment by AurelioSilver** [comment]
I doubt you need it then. It's support for a lossless video codec.

**Comment by muzicman0** [comment]
Thanks.  I have removed the 'make' section altogether, and set it to disable in the ffmpeg configuration.  It seems to be working, but won't know until it is fully done.

Thanks again for all the help!

**Comment by Warblefly** [comment]
On Wed, May 11, 2016 at 4:27 PM, muzicman0 <notifications@github.com> wrote:
> Thanks. I have removed the 'make' section altogether, and set it to disable
> in the ffmpeg configuration. It seems to be working, but won't know until it
> is fully done.

In my variant compile script, but entirely based on Roger's script,
this is what I use for libutvideo from github, if it's of any help.
This is for a shared version compiled for 64-bit Windows 10

build_libutvideo() {
  do_git_checkout https://github.com/qyot27/libutvideo.git libutvideo
  cd libutvideo
    # Utvideo calculates its version but it must be done with a
program that runs on
    # the HOST, not on the target, so its suffix must be changed to
drop the .exe
    sed -i.bak 's/$CC -o version$EXE version.c/gcc -o version
version.c/' configure
    sed -i.bak 's/version$EXE/version/' configure
    do_configure "--enable-pic --enable-shared --disable-static
--enable-asm=x64 --host=x86_64-w64-mingw32
--cross-prefix=x86_64-w64-mingw32-
--prefix=${mingw_w64_x86_64_prefix}"
    do_make
    do_make_install
    # Unfortunately, the version gets hardcoded into the filename of the .a file
    cp -fv ${mingw_w64_x86_64_prefix}/lib/libutvideo-15.1.0.dll.a
${mingw_w64_x86_64_prefix}/lib/libutvideo.dll.a
  cd ..
}

**Comment by Warblefly** [comment]
On Wed, May 11, 2016 at 4:31 PM, John Warburton <john@johnwarburton.net> wrote:

> (chopped)

Oh crumbs, lines broken all over the place.

**Comment by rdp** [comment]
Odd. For those getting the myinttypes.h failure which git commit was that
based off (or, in other words, could you pull again and make sure that's
with the latest? I thought I had run into and already fixed that one,
though possibly a few minutes after our previous conversation :)
Thanks!

**Comment by muzicman0** [comment]
I'll give it a shot in a few minutes.  

But, removing the make section and disabling it did work for me.  I completed the build (obviously without utvideo), and it works as expected.

**Comment by muzicman0** [comment]
Nope, still didn't work...same errors.

**Comment by chhe** [comment]
I can confirm `utvideo` does not compile with the latest version of `cross_compile_ffmpeg.sh`:

```
 RM     utv_core/*.o
 RM     utv_core/libutvideo.a
 CXX    utv_core/Codec.o
 CXX    utv_core/CodecBase.o
In file included from utv_core/CodecBase.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
make: *** [utv_core/CodecBase.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from utv_core/Codec.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
```

Since you thought you already fixed that error, maybe you just forgot to push the commit?

**Comment by rdp** [comment]
@chhe could you give me a bit more of the output when it fails?

**Comment by oviano** [comment]
I can confirm this error too, building on OS X.

**Comment by chhe** [comment]
Here is a complete log http://pastebin.com/hDTkRAzd

**Comment by rdp** [comment]
ok re-disabled libutvideo again till I can crack this nut :)

**Comment by ianken** [comment]
Necro thread force GO! I'm seeing the same thing or similar thing with the latest git clone.


/home/ianken/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/stdlib.h:299:0: note: this is the location of the previous definition
 #define _countof(_Array) sizeof(*__countof_helper(_Array))
 ^
In file included from utv_core/DummyCodec.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
In file included from utv_core/CodecBase.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
In file included from utv_core/GlobalConfig.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
<builtin>: recipe for target 'utv_core/CodecBase.o' failed
make: *** [utv_core/CodecBase.o] Error 1
make: *** Waiting for unfinished jobs....
<builtin>: recipe for target 'utv_core/DummyCodec.o' failed
make: *** [utv_core/DummyCodec.o] Error 1
In file included from utv_core/FrameBuffer.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
In file included from utv_core/Log.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
<builtin>: recipe for target 'utv_core/GlobalConfig.o' failed
make: *** [utv_core/GlobalConfig.o] Error 1
<builtin>: recipe for target 'utv_core/FrameBuffer.o' failed
make: *** [utv_core/FrameBuffer.o] Error 1
In file included from utv_core/Convert.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
<builtin>: recipe for target 'utv_core/Log.o' failed
make: *** [utv_core/Log.o] Error 1
<builtin>: recipe for target 'utv_core/Convert.o' failed
make: *** [utv_core/Convert.o] Error 1
In file included from utv_core/Codec.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
<builtin>: recipe for target 'utv_core/Codec.o' failed
make: *** [utv_core/Codec.o] Error 1
In file included from utv_core/HuffmanCode.cpp:4:0:
utv_core/stdafx.h:61:24: fatal error: myinttypes.h: No such file or directory
 #include <myinttypes.h>
                        ^
compilation terminated.
<builtin>: recipe for target 'utv_core/HuffmanCode.o' failed
make: *** [utv_core/HuffmanCode.o] Error 1
ianken@iank-ffbuild:~/ffmpeg-windows-build-helpers$

**Comment by rboy1** [comment]
So a few comments here, the latest version doesn't build libutvideo it given an error about missing LogWriter.h

The last working version that builds with script is version 12.2.1 or SHA1 6a9412f
If i make the script:

> do_git_checkout https://github.com/umezawatakeshi/utvideo utvideo_git 6a9412f # Last working version is 12.2.1


and uncomment the line
> sed -i.bak "s|Format.o|DummyCodec.o|" GNUmakefile

It builds.

Also a point to note, see this ticket:
https://trac.ffmpeg.org/ticket/5511

It says that it's unlikely that FFMPEG will support anything later than version 15.3.0

**Comment by rboy1** [comment]
My bad, it won't compile with the error as indicated in the first couple of posts

**Comment by rdp** [comment]
appears libutvideo was removed in favor of a native wrapper, phew!
