### ISSUE TITLE
Getting undefined reference to `pthread_mutex_lock'

### ISSUE THREAD

**Issue by garkpit** [rdp/ffmpeg-windows-build-helpers#389]
It runs for a while then spews out the error below + several hundred similar. Doesn't seem to matter which options I use. Have tried
sudo ./cross_compile_ffmpeg.sh
and
sudo ./cross_compile_ffmpeg.sh --disable-nonfree=n --compiler-flavors=win64 --high-bitdepth=y

Error message:
/home/jay/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: ./.libs/libharfbuzz.a(libharfbuzz_la-hb-blob.o):/home/jay/ffmpeg-windows-build-helpers/sandbox/win64/harfbuzz_git/src/hb-mutex.hh:133: undefined reference to `pthread_mutex_lock'

On Ubuntu Desktop 19.04 fresh install
- Followed your instructions (after installing git)
- Did this first after first run said to do it:
sudo apt-get install subversion ragel curl texinfo g++ bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev mercurial unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full python3-distutils -y
- Did sudo hoping it would help...

Might be my limited Linux knowledge, and this is obvious, but not to me :)

Thanks,
Jay

**Comment by rdp** [comment]
try latest?

**Comment by garkpit** [comment]
Yes! Works now. 
Many thanks!
Jay

**Comment by garkpit** [comment]
Hi again. So a little PS:
After getting it working on a fresh Ubuntu 19.04 I returned to my regular Linux VM which is Linux Mint 19.
The warning message "Could not find the following execs (etc)" appears as if for non-Ubuntu flavours of Linux. I suggest putting the Ubuntu message instead, as it is 100% accurate on latest Linux Mint 19 (with updates applied).
Great tool. Thanks again :)
(pps. Am now trying to get it running on Fedora Astronomy 30 but having an issue. If I don't solve it soon I will post a fresh Issue here.)

**Comment by eyahalomi** [comment]
Hi guys , I am not sure why that fix is not on the latest. I had to merge this manually to pass the build -  0fef12b

**Comment by rdp** [comment]
Please try latest, thanks!
